apiVersion: 1
datasources:
  - name: InfluxDB (chat_test)
    uid: influxdb                       # стабильный UID (опционально, но удобно)
    type: influxdb
    access: proxy
    isDefault: true
    url: http://influxdb:8086           # имя сервиса в docker-compose
    database: chat_test_telegraf        # твоя БД
    user: admin
    secureJsonData:
      password: admin
    jsonData:
      httpMode: POST
      timeInterval: 10s
