apiVersion: 1

datasources:
  # --- Источник данных для JMeter ---
  - name: InfluxDB (JMeter)
    uid: jmeter_ds
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: chat_test
    user: jmeter_user
    secureJsonData:
      password: jmeter_pass
    jsonData:
      httpMode: POST
      timeInterval: 10s
      
  # --- Источник данных для Telegraf ---
  - name: InfluxDB (Telegraf)
    uid: telegraf_ds
    type: influxdb
    access: proxy
    isDefault: true
    url: http://influxdb:8086
    database: chat_test_telegraf
    user: telegraf_user
    secureJsonData:
      password: telegraf_pass
    jsonData:
      httpMode: POST
      timeInterval: 10s
