{
 "title": "System metrics",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"usage_system\") \nFROM \"cpu\" \nWHERE $timeFilter \nGROUP BY time($interval), \"host\" fill(null)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "RAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "query": "SELECT mean(\"used_percent\") \nFROM \"mem\" \nWHERE $timeFilter \nGROUP BY time($interval), \"host\" fill(null)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Network sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "SELECT non_negative_derivative(mean(\"bytes_sent\"), 1s) AS sent\nFROM \"net\" \nWHERE $timeFilter \nGROUP BY time($interval), \"host\", \"interface\" fill(null)\n"
    }
   ]
  },
  {
   "title": "Network recv",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "SELECT non_negative_derivative(mean(\"bytes_recv\"), 1s) AS recv\nFROM \"net\" \nWHERE $timeFilter \nGROUP BY time($interval), \"host\", \"interface\" fill(null)\n"
    }
   ]
  }
 ]
}