{
 "title": "JMeter metrics",
 "time": { "from": "2025-09-04T10:24:41.267Z", "to": "2025-09-04T10:36:24.149Z" },
 "refresh": "5s",
 "panels": [
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "query": "SELECT sum(\"count\")\nFROM \"jmeter\"\nWHERE $timeFilter AND \"application\"='chat_test' AND \"transaction\"='all'\nGROUP BY time($__interval) fill(null)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "avg::field", "operator": "=", "value": "select tag value" }
     ]
    }
   ]
  },
  {
   "title": "Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "SELECT max(\"pct95.0\") AS P95,  max(\"pct90.0\") AS P90,max(\"pct99.0\") AS P99\nFROM \"jmeter\"\nWHERE $timeFilter\n  AND \"transaction\" = 'HTTP Request'\n  AND \"statut\" = 'all'\nGROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "SELECT sum(\"countError\")\nFROM \"jmeter\"\nWHERE $timeFilter\n  AND \"transaction\" = 'all'\nGROUP BY time($__interval) fill(null)\n"
    }
   ]
  },
  {
   "title": "AVG Responce Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "SELECT mean(\"avg\") AS \"AVG Response Time\"\nFROM \"jmeter\"\nWHERE $timeFilter\n  AND \"transaction\"='HTTP Request'\n  AND \"statut\"='all'\nGROUP BY time($__interval) fill(null)\n"
    }
   ]
  }
 ]
}